AUTHORS.rst, ChangeLog.rst, html2text/__init__.py, setup.py, test/empty-link.html, test/empty-link.md, test/images_to_alt.html, test/images_to_alt.md, test/img-tag-with-link.html, test/img-tag-with-link.md
Following the discussion in https://github.com/Alir3z4/html2text/issues/33.
It both allows for `<img>` tags inside anchor tags as well as empty anchor tags (eg. `<a href="google.com"></a>`) as they represent information that was being left out of the result. Also works with the `images_to_alt' flag, with the alt text being kept as the text part of the link (the previous implementation didn't allow for inline nesting of the <a> and <img> tags).
=> <a> tags with no text or <img> tags no longer discarded.

html2text/cli.py
Adds compatibility for a common way to express reading from stdin.
=> Treat '-' file parameter as stdin

html2text/__init__.py, test/html-escaping.html, test/html-escaping.md
Escaped HTML entities do not remain escaped on output.
For example:
`<p>&lt;div&gt;</p>` yields `<div>` in the output markdown, when it should yield `&lt;div&gt;`. The exception is within pre or code tags, which do not need the escaping.
This code was taken from a pull request by @brondsem on the @aaronsw repo that was never merged or closed: https://github.com/aaronsw/html2text/pull/59
=> Retain escaping of html except within code or pre tags.

ChangeLog.rst, README.md, html2text/__init__.py, html2text/cli.py, html2text/config.py, test/images_with_size.html, test/images_with_size.md, test/test_html2text.py
Given that there isn't a standard for specifying image dimensions in markdown, fall back to using raw html (sanitized to only contain src, alt, width, and height attributes) when dimensions are desired.
http://daringfireball.net/projects/markdown/syntax#img
=> Support for image sizing using raw html

.gitignore, AUTHORS.rst, html2text/__init__.py, html2text/config.py
Since this was obviously intended as seen in the design, but Daring Fireball is silent on the conversion
of automatic links, I have added an option in the module to deactivate the use of automatic links.
This way those who want it can still use it and those who prefer to follow the Daring Fireball version of MD, can opt out of the feature.
=> Issue #61. Malformed links in MD output

html2text/__init__.py, test/anchors.html, test/anchors.md
produce markdown (such as <code>, <b>, etc.).
This addresses the following issues:
https://github.com/Alir3z4/html2text/issues/63
https://github.com/Alir3z4/html2text/issues/24
=> Proper handling of anchors with content that starts with tags that

README.md, docs/usage.md, html2text/__init__.py, html2text/cli.py, html2text/config.py, test/mark_code.html, test/mark_code.md, test/test_html2text.py
For making 'pre' blocks clearer for further automatic formatting:
```
Here normal text with test code block:
[code]
use v6;
use Test;
use lib 'lib';
plan $num-tests
[/code]
Here normal text continues.
```
=> Added --mark-code option.

ChangeLog.rst, html2text/__init__.py, test/link_titles.html, test/link_titles.md
Fix for #69. Inline links now have titles in them.
=> Link titles are no longer lost in inline links.

AUTHORS.rst, ChangeLog.rst, html2text/__init__.py, test/test_html2text.py
Hey,
I believe I hit a problem with your library.
Default values for arguments are evaluated at import time.
This makes a problem when using html2text the following way:
import html2text  # The default value is evaluated here
html2text.config.BODY_WIDTH = 0
text = html2text.html2text(html)
It is thus necessary to wait until the function runs to fetch the actual
configuration value.
Thanks for maintaining html2text!
=> Make bodywidth kwarg overridable using config

ChangeLog.rst, README.md, docs/usage.md, html2text/__init__.py, html2text/cli.py, html2text/config.py, html2text/utils.py, test/no_wrap_links.html, test/no_wrap_links.md, test/no_wrap_links_no_inline_links.html, test/no_wrap_links_no_inline_links.md, test/test_html2text.py
Possible fix for #38 
- urls which are long are not wrapped if so desired.
- old behaviour is maintained to avoid breaking someone's code
- `--no-wrap-links` has been added.
- both inline links and reference links are supported for no wrapping.
- docs have been updated
=> Long links wrapping option

README.md, docs/usage.md, html2text/cli.py
Possible fix for #87 
- Decode errors can be configured via command line
=> Decode errors handling via command line.

AUTHORS.rst, ChangeLog.rst, html2text/__init__.py
This PR enables finer-grained control over the output generated. Example usage:
```python
my_em = False
def my_tag_handle(parser, tag, attrs, start):
global my_em
if tag == 'em':
if 'class' in attrs and 'my' in attrs['class'] and start:
parser.o("[my] ")
my_em = True
return True
elif my_em and not start:
parser.o("[/my]")
my_em = False
return True
parser = html2text.HTML2Text()
parser.tag_callback = my_tag_handle
text = parser.handle(html)
```
=> Add callback feature

html2text/utils.py
When set option `google_doc = True`
If element get a class, but not declared, a build-in `KeyError` exception will raise
=> :bug: fix get element style key error

html2text/__init__.py
If html contain a incorrect end tag, pop on tag_stack will raise exception
For example:
`<div></div></div>`
=> :bug: fix error end tag pop exception

ChangeLog.rst, docs/usage.md, html2text/__init__.py, html2text/cli.py, html2text/config.py, html2text/utils.py, test/pad_table.html, test/pad_table.md, test/test_html2text.py
Cell padding in Tables is added as an option to maintain backward compatibility. Solves #125
=> Table padding option

html2text/utils.py, test/google-like_font-properties.html, test/google-like_font-properties.md
Fix and tests to address CSS case-insensitive issue. Tests are specific to the google_doc flag, and all pass against master HEAD. This should fix issue #132.
=> CSS case-insensitive fix

docs/how_it_works.md, docs/usage.md, html2text/__init__.py, html2text/cli.py, html2text/config.py, test/table_ignore.html, test/table_ignore.md, test/test_html2text.py
In addition to bypassing tables, this adds an option to ignore them completely.
Only a soft_br is preserved on closing tr
=> add option to ignore tables

html2text/__init__.py, html2text/compat.py
Hello,
Python 3 raises a DeprecationWarning when using `cgi.escape`. `html.escape` is the replacement. This PR avoids the warning with a fallback to `cgi.escape` on Python 2.
Thanks!
=> Fix DeprecationWarning on Python3: use html.escape

ChangeLog.rst, html2text/__init__.py, test/images_with_div_wrap.html, test/images_with_div_wrap.md
Currently html2text will add extra line breaks while convert image links.
- What the input HTML is
```html
<a href="http://example.com"><div><img src="http://example.com/img.png"/></div></a>
```
- What the output text is
```markdown
[![](http://example.com/img.png)
](http://example.com)
```
- What we expect
```markdown
[![](http://example.com/img.png)](http://example.com)
```
This PR is to fix this problem. 
Signed-off-by: Phus Lu <phuslu@hotmail.com>
=> Fix images link with div wrap

AUTHORS.rst, ChangeLog.rst, html2text/__init__.py, test/empty-title-tag.html, test/empty-title-tag.md
This fixes issue #155 
Checks if title is none. If so, assigns an empty string to the title. Otherwise passes the title to the escape_md function.
=> Error when empty title on <a> tag

AUTHORS.rst, ChangeLog.rst, html2text/utils.py, test/bold_long_line.html, test/bold_long_line.md
The cause #143 seems a line-wrapping function confusing itemize and bold.
This PR includes a fix of the function and the corresponding test case,
which was checked with CPython 3.5.3 on Ubuntu 17.04 amd 64.
I hope it will help.
=> Fix #143: Fix line wrapping for the lines starting with bold

AUTHORS.rst, ChangeLog.rst, html2text/__init__.py, html2text/config.py, test/google-like_font-properties.html, test/google-like_font-properties.md
Google, and presumably others, use `font-weight: 700` to make bold a region of text.
This PR polls tag styles for both `bold` and `700` through `900` (via new config value,
`BOLD_TEXT_STYLE_VALUES`) before declaring text as bold or regular.
=> Adds support for "700", "800", and "900" as bold style indicators

html2text/__init__.py, test/empty-title-tag.md, test/link_titles.md
This cleans up the discrepancies between python3 and python2 functions a bit as well as refactoring a very unreadable way of how the title is being handled for links.
=> Refactor imports and title for links

AUTHORS.rst, ChangeLog.rst, html2text/utils.py, test/pad_table.html, test/pad_table.md
Current implementation simply drops cells until all rows have the lowest common length
=> Don't delete cells from tables with non-equal row lengths (e.g. using `colspan` attribute)

docs/usage.md
Adds usage documentation for `emphasis_mark` and `strong_mark`. They do not appear in config.py, but it can be useful to change them.
=> Add usage documentation for emphasis_mark and strong_mark

html2text/cli.py
`bytes.decode()` in Python 2.6 does have the errors argument, but it is positional only.
=> Simplify decoding

.travis.yml, ChangeLog.rst, README.md, html2text/__init__.py, html2text/cli.py, html2text/config.py, html2text/utils.py, requirements-dev.txt, setup.py, test/test_html2text.py, test/test_memleak.py
Python 2.6 and 3.3 are end of life. They are no longer receiving bug
fixes, including for security issues. Python 2.6 went EOL on 2013-10-29
and on 2017-09-29. For additional details on support Python versions,
see:
Supported: https://devguide.python.org/#status-of-python-branches
EOL: https://devguide.python.org/devcycle/#end-of-life-branches
Removing support for EOL Pythons will reduce testing and maintenance
resources while allowing the library to move towards a modern Python 3
style.
Using pypinfo, we can show the PyPI download statistics, show very low
numbers for EOL Pythons.
| python_version | percent | download_count |
| -------------- | ------: | -------------: |
| 2.7            |  60.79% |        251,480 |
| 3.6            |  29.19% |        120,760 |
| 3.5            |   6.70% …
=> Drop support for EOL Pythons

setup.cfg
setuptools include `README.md` as the description by default. For details, see:
https://github.com/pypa/setuptools/blob/6575418283ec605f6bca82c525f6680d897ce282/setuptools/command/sdist.py#L40-L41
=> Remove unnecessary `description-file = README.md` from setup.cfg

ChangeLog.rst, README.md, html2text/cli.py, html2text/compat.py
The feature was deprecated in commit
5672e2dd2c5bf918275acaf1142b36beba1b9ac5 (2016-05-27) and was originally
slated for removal in 2017.
Fixes #117
=> Removed long deprecated support for retrieving HTML over the network

ChangeLog.rst, html2text/__init__.py, html2text/__main__.py, setup.py, test/test_html2text.py
Allows executing the command line interface with Python's -m option:
python -m html2text ...
=> Add __main__.py file to the package

setup.py
Remove include_package_data. The package does not contain any data
files, only Python files.
Remove zip_safe. As the package does not contains any data files, it is
zip safe.
=> Remove unused options from setup.py

.gitignore, test/test_html2text.py
Unused since 9125b6c5261f5cb5fde5b9d22ee121d2920813bf. Nothing dumps
output files.
=> Remove unused get_dump_name()

ChangeLog.rst
Requires two back-quotes, not one.
http://docutils.sourceforge.net/docs/user/rst/quickstart.html#text-styles
=> Correct fixed-space literal rst syntax

tox.ini
Previously was missing py37 and some targets had too many "py"
substrings.
=> Correct default tox matrix

docs/how_it_works.md, html2text/__init__.py
The function is empty, same as the parent class's implementation. Just
use inheritance rather than re-defining it.
=> Remove unused method unknown_decl

html2text/__init__.py
The file is not executable, no should not be executed directly, but as
python -m html2text ...
Or from the setuptools installed entry point.
=> Remove shebang from __init__.py

.travis.yml, html2text/__init__.py, html2text/cli.py, html2text/compat.py, setup.cfg, test/test_html2text.py, tox.ini
This tool automates import sorting across Python files. This removes the
need for contributors to think about the project's styling preferences
for imports. Just let the tool do it instead.
isort is a well established tool used by many projects.
https://github.com/timothycrosley/isort
=> Introduce isort for automated consistent sorting of Python imports

html2text/__init__.py
As the file imports unicode_literals, all literal strings are unicode
objects by default. The coerce is a noop.
=> Remove unnecessary coerce to unicode()

html2text/__init__.py
The value is being used as a boolean for branching, so use a boolean
rather than an int. Easier to understand for the reader.
Additionally, always use a keyword argument rather than a bare 0/1 or
False/True to provide context to the reader.
=> Use bool in HTML2Text.o() rather than int 0/1

html2text/utils.py
Replace pattern:
if <boolean expression>:
return True
return False
With
return <boolean expression>
=> Simplify the return of boolean expressions

html2text/utils.py
The new form:
- Avoids the unnecessary `range()` call. On Python 2 this avoids building the data structure in memory.
- Avoids the `try`/`except` block. The comparison is required either way, so just do that from the start.
- Always explicitly return as a value. The old form sometimes fell through and returned `None`.
The new version is also slightly faster. Running the function through Python's `timeit` showed the following results:
old: 0.6434267910080962
new: 0.40665965899825096
=> Simplify hn() function

html2text/__init__.py
Reuse the previous value instead.
=> Remove unnecessary duplicate call to name2cp()

html2text/__init__.py
Can remove the `else` after the return to dedent the block.
=> Simplify entityref()

ChangeLog.rst, html2text/__init__.py, test/test_memleak.py
Previously, after the first `abbr` tag, the `abbr_data` attribute continued
to grow when processing additional data. Now set the attribute to `None`
to avoid appending the unused data.
=> Fix memory link when processing an abbr tag

ChangeLog.rst
Need a space before and after the indented list.
=> Correct nested list syntax in changelog

html2text/__init__.py
Always return an explicit value.
=> Simplify pareviousIndex by using enumerate()

html2text/utils.py
Short-circuit evaluation when `wrap_links` is True (the default). Evaluating a boolean expression is much cheaper than searching a paragraph for a match.
Any link present in the paragraph causes the wrapping to be skipped. Instead of searching for all matches, stop at the first match.
---
Suggesting the PR after encountering a catastrophic case at work today. `html2text` took 3800 seconds to generate the plain-text version of a 20 MB HTML document that contained many `[]` and `()`. With this patch applied, it processes the input in less than 10 seconds.
=> Speed up skipwrap function

setup.cfg, test/test_html2text.py, tox.ini
- flake8 ignores W503 by default
- Use isort profile to simplify configuration
- Update isort CLI invocation for 5.* series
=> Simplify and update lint configurations

AUTHORS.rst, ChangeLog.rst, html2text/__init__.py, test/empty-link.md, test/link_titles.html
The following HTML code
```
<a href="http://example.com" title="MyTitle"> first example</a>
<br>
<a href="http://example.com" ><p> second example</p></a>
```
is being converted by `html2text` version (2020, 1, 16) to the following Markdown (notice in the second example the line break before the closing `]`):
```
[ first example](http://example.com "MyTitle")  
[ second example
](http://example.com)
```
or with inline_links = False:
```
[ first example][1]  
[ second example
][2]
[1]: http://example.com (MyTitle)
[2]: http://example.com
```
The additional line break, besides looking askew, doesn't seem to be allowed by the official [specs](https://daringfireball.net/projects/markdown/syntax#link), and indeed breaks converting Markdown back to HTML.
This PR fixes the code to produce the …
=> Don't add line breaks inside link names

index.html
I have changed the link of docs to https://github.com/Alir3z4/html2text/blob/master/docs/usage.md
=> Fixed broken link of docs

html2text/__init__.py, test/br_inside_a.html, test/br_inside_a.md
Fix Markdown links being broken by HTML where the link text includes a `<br>` (as seen in the wild).
Example:
```
<a href="https://example.org/">This is a<br>test</a>`
``` 
is output as
```
[This is a
test](https://example.com)
```
Whis is **not** a Markdown link.
After this PR the output is:
```
[This is a test](https://example.com)
```
Whis is a **valid** Markdown link.
=> Fix \n inside text of a Markdown link

html2text/__init__.py, test/test_newlines_on_multiple_calls.py
- The bug was being caused since `self.start` was retaining the `False` value
- I've added tests to ensure this does not regress.
=> Fix extra newline bug

.github/workflows/main.yml
=> Fix CI for Python 3.12

.github/workflows/pypi.yml
Closes https://github.com/Alir3z4/html2text/issues/418
See https://docs.pypi.org/trusted-publishers/adding-a-publisher/ for setting up trusted publisher for authentication
=> ci: publish wheels to pypi

.github/workflows/main.yml, .github/workflows/pypi.yml, tox.ini
Have to upgrade the tools and remove old tooling before performing a release.
=> Upgrade Build Tools to Latest
